[SERVICE]
    Flush               1
    Log_Level           info
    Parsers_File        /etc/fluent-bit/parsers.conf


[INPUT]
    Name                tail
    Path                /var/log/cas/cas_audit.log
    multiline.parser    inspektr_audit
    Tag                 cas.audit
    DB                  /etc/fluent-bit/db/cas_audit.db
    DB.Sync             Normal
    Read_From_Head      On
    Skip_Empty_Lines    On
    Refresh_Interval    5
    Buffer_Chunk_Size   32k
    Buffer_Max_Size     256k

[FILTER]
    Name    lua
    Match   cas.audit
    script  /etc/fluent-bit/cas-audit.lua
    call    parse_audit


[OUTPUT]
    Name                opensearch
    Match               cas.audit
    Host                os.example.foo
    Port                443
    HTTP_User           test_entrust_writer
    HTTP_Passwd         **************
    Logstash_Format     On
    Logstash_Prefix     test-entrust-cas-
    Logstash_DateFormat %Y-%m-%d
    tls                 On
    tls.verify          Off
    Suppress_Type_Name  On

# Output to a new log file
#[OUTPUT]
#    Name          file
#    Match         cas.audit
#    Path          /var/log/cas/output/
#    File          cas_audit.out.log

# Output to stdout 
#[OUTPUT]
#    Name           stdout
#    Match          *
#    Format         json_lines
